// AUTO-GENERATED by scripts/generate-voiceover.ts. Do not edit by hand.
// Frames derived from real ElevenLabs audio durations (音频先行).
export type GeneratedBeat = { id: string; startFrame: number; durationInFrames: number; durationSeconds: number };
export const generatedBeats: GeneratedBeat[] = [
  {
    "id": "b1_hook",
    "startFrame": 0,
    "durationInFrames": 226,
    "durationSeconds": 7.523
  },
  {
    "id": "b2_setup",
    "startFrame": 226,
    "durationInFrames": 196,
    "durationSeconds": 6.504
  },
  {
    "id": "b3_turn",
    "startFrame": 422,
    "durationInFrames": 262,
    "durationSeconds": 8.725
  },
  {
    "id": "b4_reversal",
    "startFrame": 684,
    "durationInFrames": 365,
    "durationSeconds": 12.147
  },
  {
    "id": "b5_cta",
    "startFrame": 1049,
    "durationInFrames": 201,
    "durationSeconds": 6.687
  }
];
