// AUTO-GENERATED by scripts/generate-voiceover.ts. Do not edit by hand.
// Frames derived from real ElevenLabs audio durations (音频先行).
export type GeneratedBeat = { id: string; startFrame: number; durationInFrames: number; durationSeconds: number };
export const generatedBeats: GeneratedBeat[] = [
  {
    "id": "b1_hook",
    "startFrame": 0,
    "durationInFrames": 234,
    "durationSeconds": 7.784
  },
  {
    "id": "b2_setup",
    "startFrame": 234,
    "durationInFrames": 212,
    "durationSeconds": 7.053
  },
  {
    "id": "b3_turn",
    "startFrame": 446,
    "durationInFrames": 262,
    "durationSeconds": 8.725
  },
  {
    "id": "b4_reversal",
    "startFrame": 708,
    "durationInFrames": 368,
    "durationSeconds": 12.251
  },
  {
    "id": "b5_cta",
    "startFrame": 1076,
    "durationInFrames": 232,
    "durationSeconds": 7.706
  }
];
